- id: doi:10.1007/978-3-030-98015-3_10
  image: https://media.springernature.com/lw685/springer-static/image/chp%3A10.1007%2F978-3-030-98015-3_10/MediaObjects/518004_1_En_10_Fig2_HTML.png?as=webp
  
- id: doi:10.1007/978-3-030-97610-1_6
  image: https://signofthefour.github.io/images/CalibStyelSpeech.png
  
- id: doi:10.1109/NICS56915.2022.10013451
  image: https://signofthefour.github.io/images/bahnar.png
